# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Pe0GnCA+2gO8u+Z4BF6J77tKibhtscup2pSIRcNNBdznngv4kGCkoI7tnK9N9LSVt0AbcWVt9s+SvLyxQeKy6LR9ln+xi+B8EwxD986LvlqFDLSsM+PGJoIUR7Y6cej2rFDa6TF0Sju5NHjm8RjdoETIqydWNmoSv/kr9FCUX9OE7oJshdU7K3HOfV5Pk2gCrwr5Z/ZPCcxS0BQp3B/s4m1BRh8bz0Qb6sh9eUKHwlKfYnontcUDUqBmE8gD1+KCquGKn8ej1CUqOF4DMSiZEs7CGiSKlnUT6vQJkOc1lNtYDOm1EJrM7h+lXHcAsI2GoP34IiFKW4cYOkZE47Ufdnx2sKZ1WchdqsT+Y2RHffTNu3RboMytiHuKZllqAlV1LX2yCaeBnGCxchqYd3CbRn5ih+akqW3Le9z+5rfCIbG9kIN+qw7kfa9lp7SIXbzP6wUybts1GnUOhHTvMvrrz86nKtY8Qx6zc/batRW3lZoWoHYp5/sqw249UPm3nexLZ1V74Tw/4HJJffHup5pAmmFgRsY06JgDknKaWPIr/SM35nwSjSMsqjHJNPgWia6oukT71llZWgcIIt/dfj5hUhHdxm06GM+5rlDgBznnEp8PxGqGTVuQI9egfsAsZJwAQovQ8ZrzF3RwRVIInT/9ybeIZLwkr/lw9urn2zergXw="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
