travis:
  secure:
    BINSTAR_TOKEN: Pe0GnCA+2gO8u+Z4BF6J77tKibhtscup2pSIRcNNBdznngv4kGCkoI7tnK9N9LSVt0AbcWVt9s+SvLyxQeKy6LR9ln+xi+B8EwxD986LvlqFDLSsM+PGJoIUR7Y6cej2rFDa6TF0Sju5NHjm8RjdoETIqydWNmoSv/kr9FCUX9OE7oJshdU7K3HOfV5Pk2gCrwr5Z/ZPCcxS0BQp3B/s4m1BRh8bz0Qb6sh9eUKHwlKfYnontcUDUqBmE8gD1+KCquGKn8ej1CUqOF4DMSiZEs7CGiSKlnUT6vQJkOc1lNtYDOm1EJrM7h+lXHcAsI2GoP34IiFKW4cYOkZE47Ufdnx2sKZ1WchdqsT+Y2RHffTNu3RboMytiHuKZllqAlV1LX2yCaeBnGCxchqYd3CbRn5ih+akqW3Le9z+5rfCIbG9kIN+qw7kfa9lp7SIXbzP6wUybts1GnUOhHTvMvrrz86nKtY8Qx6zc/batRW3lZoWoHYp5/sqw249UPm3nexLZ1V74Tw/4HJJffHup5pAmmFgRsY06JgDknKaWPIr/SM35nwSjSMsqjHJNPgWia6oukT71llZWgcIIt/dfj5hUhHdxm06GM+5rlDgBznnEp8PxGqGTVuQI9egfsAsZJwAQovQ8ZrzF3RwRVIInT/9ybeIZLwkr/lw9urn2zergXw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
